Friends
supernova-97/Capstone-Project pull request #12
Opened 2023-04-05 08:55 UTC by supernova-97

friends (hardcoded for now) can be assigned todos via the dropdown menu

2023-04-05 09:21 UTC, actyralf requested changes
Great work!
Please have a look on my comments (mostly regarding naming...).

2023-04-05 09:21 UTC, actyralf commented on components/Form/index.js
> +function Form({ onAddToDo, tripData, setSelectedFriend, selectedFriend }) {
please follow the convention to prefix callbacks with `on`, e.g. `onSelectFriend` instead of `setSelectedFriend`

2023-04-05 09:21 UTC, actyralf commented on components/Form/index.js
> +  // const [selectedFriend, setSelectedFriend] = useState(tripData.who[0]);
please remove unused code

2023-04-05 09:21 UTC, actyralf commented on components/List/index.js
> +        {/* <ul>
please remove unused code

2023-04-05 09:21 UTC, actyralf commented on pages/_app.js
> +  const [selectedFriend, setSelectedFriend] = useState(tripData.who[0]);
This works because you initialized `tripData` with a dummy record. It will not work when you start empty.
Did you consider this?

2023-04-05 09:21 UTC, actyralf commented on pages/new-trip/index.js
> +      />
Why does `NewTrip` need existing trip data? Is it used to create new trips AND edit existing ones? Then I would rename it (e.g. `TripForm`).
Instead of `setTripData` I would also follow the `on...` convention for callback props: e.g. `onCreateTrip` or `onSubmitTrip`

2023-04-05 10:09 UTC, supernova-97 commented on pages/_app.js
> +  const [selectedFriend, setSelectedFriend] = useState(tripData.who[0]);
It works as soon as the input field "who is coming" is filled out. I guess I should display the form first when you open the app and as soon as its filled out you'll be directed to the dashboard. That way, all the components will function because the data is there

2023-04-05 10:16 UTC, supernova-97 commented on pages/new-trip/index.js
> +      />
It needs the global state "tripData" because NewTrip defines it. Initially the tripData had no values, but since it was too annoying to always completely fill out the form to test one input field I just hardcoded the data

2023-04-05 12:13 UTC, toshydev approved these changes
LGTM, nice structuring 💪

2023-04-06 09:33 UTC, djfarly approved these changes
lgtm :) just some minor notes below.
keep going!

2023-04-06 09:33 UTC, djfarly commented on components/List/index.js
> +          <StyledSection key={friend}>
Just a heads-ups: This code will break as soon as you have two friends with the same name, because more than one child element will have the same key.

2023-04-06 09:33 UTC, djfarly commented on components/NewTrip/index.js
> +  console.log("tripDataWho:", tripData.who);
It's best not to merge testing `console.log`s into main.
```suggestion
```

2023-04-06 09:33 UTC, djfarly commented on components/NewTrip/index.js
> +    console.log(separatedArray);
```suggestion
```

2023-04-06 09:59 UTC, merged