To do checked
supernova-97/Capstone-Project pull request #7
Opened 2023-03-29 13:56 UTC by supernova-97

Changes styling of checked to-dos

2023-03-29 14:09 UTC, LuYujin9 approved these changes
Your app looks cool.

2023-03-29 14:16 UTC, stefankorder requested changes
Good work! Just a little hint.

2023-03-29 14:16 UTC, stefankorder commented on components/List/index.js
> +// `;
Please delete code you don't use anymore.

2023-03-29 14:36 UTC, supernova-97 commented on components/List/index.js
> +// `;
Yep, got rid of it 👍🏻

2023-03-30 06:58 UTC, supernova-97 commented
Checked to do will be crossed out

2023-03-30 06:58 UTC, merged